spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        partition.assignment.strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
    properties:
      spring.json.trusted.package: com.tianjian.kafka.bean
  thymeleaf:
    prefix: classpath:/templates/
  redis:
    #数据库索引
    database: 0
    host: redis
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000
    #邮箱配置

kafka:
  topic: ${random.value}

jwt:
  key: TWFydGVsbEtwaURPVG9WTw==
  md5-key: MD5KEY

server:
  port: 8082