spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/mysql?Unicode=true&characterEncoding=UTF-8&useSSL=false
    #url: jdbc:mysql://119.3.107.239:3306/mysql?Unicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: abc123
  jpa:
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: update
    hibernate:
      ddl-auto: update

#  data:
#    neo4j:
#      username: neo4j
#      password: tianjian
#      uri: bolt://127.0.0.1:7687
#    mongodb:

  redis:
    #数据库索引
    database: 0
    host: redis
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000
    #邮箱配置

  mail:
    host: smtp.qq.com
    username: 917484312@qq.com
    #QQ邮箱的授权码
    password: 自己申请
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  key: TWFydGVsbEtwaURPVG9WTw==
  md5-key: MD5KEY
server:
  port: 8083
