spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.3.107.239:3306/mysql?Unicode=true&characterEncoding=UTF-8&useSSL=false
    #url: jdbc:mysql://mysql:3306/mysql?Unicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: abc123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        partition.assignment.strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor

server:
  port: 8081